services:
  php:
    build: .
    container_name: airtable-orm-php
    volumes:
      - .:/app
    working_dir: /app
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    command: tail -f /dev/null
    
  test:
    build: .
    container_name: airtable-orm-test
    volumes:
      - .:/app
    working_dir: /app
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    command: vendor/bin/phpunit tests --testdox
